### PR TITLE
Bump terra-notebook-utils to version 0.7.0

### PR DESCRIPTION
**Pull request by xbrianh**

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]

**Comment by Qi77Qi** [comment]
thanks @xbrianh for contributing..do you have any specific reason for bumping the version? just wonder if there's any so that we can mention it in terra release notes

**Comment by xbrianh** [comment]
Hi @Qi77Qi terra-notebook-utils is the provided DRS client for notebook and terminal users. Keeping it up to date should provide a more consistent UX. The old version was quite stale compared to [currently provided documentation](https://support.terra.bio/hc/en-us/articles/360039330211).

**Comment by rtitle** [comment]
FYI @xbrianh this should be in Terra prod now, if you create a new runtime.

**Comment by xbrianh** [comment]
@rtitle Great, thanks!

**Pull request merged**
