### PR TITLE
AoU image: Drop gatk jar, statsmodel, bigrquery override

### PR DESCRIPTION
**Pull request by calbach**
Also tried upgrading plotnine, but this causes conflicts with pandas 1.0 (Hail requires a lower version).

@ericsong @deflaux FYI

### CODE REVIEW

**Review by rtitle — APPROVED** [review]
LGTM, I'll defer to you on the AoU image testing.

Once merged this should trigger a new Leo custom image build with this version + the old version cached.

**Comment by Qi77Qi** [comment]
@calbach do you plan to test this? if yes, let me know, I'll merge after that...if not, we can merge it and let it go through automation tests as well (slightly more work if tests don't pass)

**Comment by deflaux** [comment]
These changes lgtm.

Another change to consider: the [pandas_profiling snippet](https://github.com/all-of-us/workbench-snippets/blob/master/dataset-snippets/summarize_a_dataframe.py) is broken on the current AoU image. I know that using more recent versions of pandas, pandas-profiling, etc. fixes the issue, but I haven't yet checked whether a lesser update will fix it for the old version of pandas.

**Comment by calbach** [comment]
Thanks - @Qi77Qi I am still doing some final testing on this, please hold on merging (is it fine if I merge this when ready instead?).

@deflaux will the smoke tests cover that breakage? Either way I'll try the snippet as well.

**Comment by Qi77Qi** [comment]
@calbach sure yea...you can merge it as well....maybe just slack me or something when you do, and I'll get it to prod

**Comment by calbach** [comment]
Sorry for the delay - finally had a chance to circle back and test this. I think this version is good to go, feel free to merge whenever, I will let you all merge in case anything changed since I originally sent this.

**Comment by calbach** [comment]
Merging. Would like to make this the "next" version in Leo, and make `broadinstitute/terra-jupyter-aou:1.0.14` the "old" one, let me know if I should be sending additional PRs to make that part happen.

**Comment by rtitle** [comment]
Thanks @calbach  - I think that should all happen automatically, can keep and eye on CI.

**Pull request merged**
