### PR TITLE
Update genomics tools on AoU image

### PR DESCRIPTION
**Pull request by calbach**
- Add a variantstore cohort extract script
- Update the GATK custom built jar

AoU ticket: https://precisionmedicineinitiative.atlassian.net/browse/RW-5764

### CODE REVIEW

**Comment by calbach** [comment]
@ericsong PTAL as well

**Review by Qi77Qi — APPROVED** [review]

**Review by ericsong — APPROVED** [review]

**Comment by Qi77Qi** [comment]
@gpcarr can you try to get this change in leo since you're UL this week? once this is merged, there will be auto PRs as usual, but for aou, we'll need to bump the latest version cached for aou

question to @calbach , what version do you guys use in prod right now?

**Comment by calbach** [comment]
@Qi77Qi currently we're on 1.0.11

FYI https://broadworkbench.atlassian.net/browse/IA-2247 tracks caching two AoU images for GCE. Unfortunately we will have slow runtime creations during the rollout process without this, but we will switch to this version next week.

**Comment by gpcarr** [comment]
> @gpcarr can you try to get this change in leo since you're UL this week? once this is merged, there will be auto PRs as usual, but for aou, we'll need to bump the latest version cached for aou
> 
> question to @calbach , what version do you guys use in prod right now?

hey @Qi77Qi and @calbach I'm just seeing this now, my bad! I'll make sure to test these changes tomorrow

**Comment by calbach** [comment]
Hi @gpcarr , I actually found a bug in this version, so you can ignore .13 and we'll hopefully be skipping straight to .14.

New correct versions for caching purposes will be:
- AoU "old": 1.0.11
- AoU "current": 1.0.14

**Comment by gpcarr** [comment]
> Hi @gpcarr , I actually found a bug in this version, so you can ignore .13 and we'll hopefully be skipping straight to .14: #167.
> 
> New correct versions for caching purposes will be:
> 
> * AoU "old": 1.0.11
> * AoU "current": 1.0.14

Sounds good, looks like this is the corresponding Leo PR: https://github.com/DataBiosphere/leonardo/pull/1663/files I'll make sure to keep an eye on tests and get that merged tomorrow

**Pull request merged**
