### PR TITLE
[SU-293] Fix Jupyter Lab build message on start

### PR DESCRIPTION
**Pull request by MatthewBemis**

### CODE REVIEW

**Review by jdcanas — APPROVED** [review]

**Comment by jdcanas** [comment]
Oh yeah, as mentioned in the comment here, https://broadinstitute.slack.com/archives/CA3NP1733/p1677602592219319?thread_ts=1677594855.010879&cid=CA3NP1733, you'll need to:

- You need to bump conf.json for your new terra-jupyter-base version, and update Changelog.md  and VERSION file in the terra-jupyter-base dir
- you’ll need to run updateVersions.sc in terra-docker to bump all images dependent on the base.

**Review by jdcanas — CHANGES_REQUESTED** [review]
See above comment

**Comment by jdcanas** [comment]
Looks like you still need to run `updateVersions.sc` to update all images that depend on `terra-jupyter-base`

**Review by jdcanas — APPROVED** [review]

**Comment by MatthewBemis** [comment]
Merged despite AoU and gatk-ovtf builds failing. AoU is known to be broken and gatk-ovtf failed for disk space reasons and that image is being deprecated anyway

**Comment by yonghaoy** [comment]
failed to solve with frontend dockerfile.v0: failed to create LLB definition: us.gcr.io/broad-dsp-gcr-public/terra-jupyter-gatk:2.2.11
And I checked in GCP console, seems image does not exist in GCP. Just kicked off a GHA to make a new push.

**Comment by yonghaoy** [comment]
> Reference

I don't think AoU is known to be broken. Seems AoU build is broken after this PR: https://github.com/DataBiosphere/terra-docker/actions/workflows/test-terra-jupyter-aou.yml

**Pull request merged**
