### PR TITLE
Fix the Hail Dockerfile

### PR DESCRIPTION
**Pull request by danking**
We started using pip system specifiers (e.g. ; sys_platform != 'win32') which was causing issues with xargs. Writing a file and running on the file seems simpler anyway.

### CODE REVIEW

**Review by calbach — APPROVED** [review]
Thanks. Please check my understanding: the prior approach was not yet a problem, but would be on a future version of Hail.

**Comment by danking** [comment]
Yeah that's exactly right @calbach. 0.2.94 includes the sys_platform change.

**Comment by danking** [comment]
Hmm, seems like the docker build inadvertently triggered an update of some part of Jupyter:
```
KeyError: 'The Python module igv is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
```

**Comment by calbach** [comment]
Trying that fix here: https://github.com/DataBiosphere/terra-docker/pull/335

**Comment by calbach** [comment]
Merged #335  with fix, hopefully this PR should be good on rebase.

**Comment by danking** [comment]
@calbach fwiw, I think checks are not required on this repo right now (I still see the squash and merge button).

**Comment by calbach** [comment]
I don't know if that's intended or not, I merely have some authority over this image in particular, not the overall repo. @Qi77Qi FYI

**Review by Qi77Qi — APPROVED** [review]

**Pull request merged**
