### PR TITLE
terra-jupyter-r:0.0.12

### PR DESCRIPTION
**Pull request by nturaga**
- Create new entry in CHANGELOG file.

- This image will include most of CRAN and Bioconductor system dependencies.

- Makes the notebook actually useable by analysts.

- Remove Bioconductor packages

- Add environment variables R_PLATFORM and R_PLATFORM_BINARY_VERSION, these are needed to make the binary package installation of R packages.

### CODE REVIEW

**Comment by Qi77Qi** [comment]
https://github.com/DataBiosphere/terra-docker/blob/master/config/conf.json needs to be updated as well..also are you planning on updating bioconductor image, gatk image and aou image as well to use the new R image?

**Comment by nturaga** [comment]
> https://github.com/DataBiosphere/terra-docker/blob/master/config/conf.json needs to be updated as well..also are you planning on updating bioconductor image, gatk image and aou image as well to use the new R image?

I'll update this. 

And yes, i'll update the bioconductor image, gatk image and aou image as well. It would be simply changing the version numbers in the gatk and aou images. The bioconductor image will come with some significant differences.

**Comment by nturaga** [comment]
@Qi77Qi Should I put them all in this PR?

**Comment by Qi77Qi** [comment]
@nturaga maybe better to put them in a separate PR just so we can have this change go through automation tests first and validated?

**Pull request merged**
