### PR TITLE
[RW-7392]Move nextflow into a right location

### PR DESCRIPTION
**Pull request by yonghaoy**
User does not have permission on user/bin/
Then I followed above example (plink) and put it in a new dir. 

I followed the tutorial here: https://github.com/DataBiosphere/terra-docker#testing-your-image-manually
But it is still accessing terminal as root. Not sure if that will work in the real case, but based on plink example, the new way should work.

### CODE REVIEW

**Review by calbach — APPROVED** [review]
The docker example CLI should work with non-root if you just leave `-u` unspecified (jupyter should be the default). Alternatively you can try -u jupyter

**Comment by yonghaoy** [comment]
> The docker example CLI should work with non-root if you just leave `-u` unspecified (jupyter should be the default). Alternatively you can try -u jupyter

Interesting, now I got the permission error back:
```
➜  terra-jupyter-aou git:(yonghaoy-patch-1) docker run --rm -it -u jupyter -p 8000:8000 --entrypoint /bin/bash aou-yyu-test
jupyter@f0d5f86d8b61:~$ nextflow
bash: /bin/nextflow: Permission denied

```

**Comment by yonghaoy** [comment]
> > The docker example CLI should work with non-root if you just leave `-u` unspecified (jupyter should be the default). Alternatively you can try -u jupyter
> 
> Interesting, now I got the permission error back:
> 
> ```
> ➜  terra-jupyter-aou git:(yonghaoy-patch-1) docker run --rm -it -u jupyter -p 8000:8000 --entrypoint /bin/bash aou-yyu-test
> jupyter@f0d5f86d8b61:~$ nextflow
> bash: /bin/nextflow: Permission denied
> ```

Then I checked pink's permission, and grant the same permission to nextflow:
```
root@4930f3abd5d8:/bin# ls -l plink
-rwxrwxr-x 1 root root 41656168 Apr 17  2021 plink

root@4930f3abd5d8:/bin# chmod u=rwx,g=rwx,o=rx nextflow
root@4930f3abd5d8:/bin# ls -l nextflow
-rwxrwxr-x 1 root root 15746 Dec  2 22:15 nextflow
```

**Comment by calbach** [comment]
I'm not sure if it's working or not for you -let me know if you want me to pull this PR and try locally

**Comment by yonghaoy** [comment]
> I'm not sure if it's working or not for you -let me know if you want me to pull this PR and try locally

I followed plink permission, and grant the same thing to nextflow and now it works. (I think others need to have read access on that file, previous it is just execute permission. )
But the issue I am facing is the terra-jupyer-python test fails consistently. 
The logs can be found at the `Artifacts` part
on the bottom of https://github.com/DataBiosphere/terra-docker/actions/runs/1533043904 

The errors are about 
`[Errno 13] Permission denied: '/tmp/credentials.json'` it is similar, but I don't think my PR changes that part...

**Comment by calbach** [comment]
@yonghaoy I'm suspicious of this master branch dependency on setup-gcloud: https://github.com/DataBiosphere/terra-docker/blob/master/.github/workflows/test-terra-jupyter-aou.yml#L56, there are some recent commits here that look relevant:

https://github.com/DataBiosphere/terra-docker/blob/master/.github/workflows/test-terra-jupyter-aou.yml#L56


Maybe try pinning us to an older commit like `7a6c78`

**Comment by yonghaoy** [comment]
> google-github-actions/setup-gcloud#405

It does work! Initially I thought the issue is fixed in https://github.com/google-github-actions/setup-gcloud/pull/412
I will ask in that PR.

**Pull request merged**
