### PR TITLE
update to hail 0.2.85

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
Hey there friends! We're experimenting with automatically issuing a pull request against this repo in our release process. It looks like we need to actually to push the branch to DataBiosphere (not our fork) before making the PR. I'll fix this in our release process.

**Comment by Qi77Qi** [comment]
sounds great..thanks @danking ! btw https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-hail/Dockerfile#L7 needs to be updated as well

**Comment by danking** [comment]
@Qi77Qi , it appears my user account does not have permission to make a PR into databiosphere/terra-docker. Can you grant me permission?

**Comment by danking** [comment]
This is the bot: https://github.com/hail-tester1

**Comment by Qi77Qi** [comment]
@danking added both...think both invites are waiting for confirmation

**Pull request closed without merging**
