### PR TITLE
[ID-1352] Update TNU version in Dockerfile

### PR DESCRIPTION
**Pull request by samanehsan**
Use latest version 0.14: https://pypi.org/project/terra-notebook-utils/0.14.0/ which has the following [changes](https://github.com/DataBiosphere/terra-notebook-utils/blob/master/Changes.md#changes-for-v0140-2024-09-03)

### CODE REVIEW

**Review by LizBaldo — CHANGES_REQUESTED** [review]
@samanehsan the change looks good, but you need to bump up the version of all of the docker containers appropriately, see CONTRIBUTING.md

**Comment by LizBaldo** [comment]
Here is a previous PR updating TNU that should be a good baseline https://github.com/DataBiosphere/terra-docker/pull/449

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Comment by LizBaldo** [comment]
Thanks! Let's see if the tests are passing, I can move this PR along if needed

**Comment by samanehsan** [comment]
@LizBaldo there are two tests failing but I don't quite understand the errors. Could you take a look?

**Comment by LizBaldo** [comment]
Yep, I am on it and will move the PR along :)

**Comment by LizBaldo** [comment]
@samanehsan and @tlangs how critical is the release of TNU 14? As you can see, this PR is getting very unwieldy and I think it is about time that I refactor the base image first, and this whole process frankly. But that might take me a sprint or so, hence delaying the release of TNU further

**Comment by samanehsan** [comment]
@LizBaldo it's not super urgent so it can wait a sprint or two. The release includes these two changes:
1) Notebooks will tell DrsHub the cloud they are running on to cut down on unnecessary egress costs
2) Notebooks will pass in a "service-name" header so DrsHub can show how many requests are coming from notebooks in our product metrics dashboard (requested by stakeholders)

**Comment by LizBaldo** [comment]
@samanehsan FYI things are looking almost ready to ship, finally :) If you don't mind giving the sister PR in Leonardo a review that would be awesome, thanks! https://github.com/DataBiosphere/leonardo/pull/4784

**Review by LizBaldo — APPROVED** [review]

**Pull request merged**
