### PR TITLE
AoU: Download gatk jar instead of building

### PR DESCRIPTION
**Pull request by calbach**
This should massively reduce the resource requirements for building this image, per

- https://broadworkbench.atlassian.net/browse/IA-2221
- https://broadworkbench.atlassian.net/browse/DDO-752

### CODE REVIEW

**Comment by calbach** [comment]
CC @ericsong @ahaessly

**Review by rtitle — APPROVED** [review]
Looks reasonable to me - I wonder if we should adopt this in `terra-jupyter-gatk` as well

**Comment by calbach** [comment]
`terra-jupyter-gatk` already downloads the zip from the gatk releases, so it's effectively doing the same thing. I just need to grab it from a different location because this is a branched version of the jar - later this will be merged into the main line and we can use the same approach as `terra-jupyter-gatk`, probably just doing a `COPY` from it.

**Comment by rtitle** [comment]
BTW @calbach -- I suspect you're testing these images yourself, but we can also bump the version [here](https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/resources/reference.conf#L5) to run Leo automation tests against the latest and greatest AoU image.

**Pull request merged**
