### PR TITLE
Minor edits to Dockerfile in R package installation

### PR DESCRIPTION
**Pull request by nturaga**
Install "remotes" and "devtools" with BiocManager::install()

### CODE REVIEW

**Comment by Qi77Qi** [comment]
will this cause any version change?

**Comment by nturaga** [comment]
> will this cause any version change?

No, there will be no version changes. This is just a small modification to follow best practices to have the installation be done in the right places.

**Comment by nturaga** [comment]
Although the R version in the `rstudio/rstudio-server-pro:1.2.5042-1` image which this inherits from is outdated and is R-3.6.3. 

Ideally we would get R-4.0 which is the current release version of R. @rtitle Can you comment on this? Does RStudio have a newer image?

**Comment by rtitle** [comment]
> will this cause any version change?
We haven't started versioning RStudio Pro yet; need to set that up and push an initial `0.0.1` version

**Comment by rtitle** [comment]
> Does RStudio have a newer image?

That's a great question. I don't see R 4.0.0 support in https://github.com/rstudio/rstudio-docker-products. This might be a good question for the RSP support team, I could make a case and cc you

**Comment by nturaga** [comment]
Thanks @rtitle , that would be great to be cc-ed on it.

**Comment by Qi77Qi** [comment]
think this PR is outdated....going to close...feel free to reopen if I missed sth

**Pull request closed without merging**
