### PR TITLE
RW-8725 Add QIMEE2 to Jupyter VM Image

### PR DESCRIPTION
**Pull request by tarekmamdouh**

### CODE REVIEW

**Comment by yonghaoy** [comment]
@Qi77Qi test fails because no space left. I think we had the same issue before (https://broadinstitute.slack.com/archives/CADM7MZ35/p1654867015705949)
 and DevOps created https://broadworkbench.atlassian.net/browse/DDO-2129 and that one marked as done. 
Any suggestion on how to fix this space issue?

**Review by yonghaoy — COMMENTED** [review]
See https://github.com/DataBiosphere/terra-docker/pull/350#pullrequestreview-1098121318
depends on which PR get merged first, we probably will use 2.1.10 or 2.1.11

**Comment by Qi77Qi** [comment]
@yonghaoy 2.1.9 is fine to use. regarding https://github.com/DataBiosphere/terra-docker/pull/350, I think it's probably easier just to have the hail version bump in this PR as well...think Daniel's PR is just doing us a favor...

**Comment by yonghaoy** [comment]
> @yonghaoy 2.1.9 is fine to use. regarding #350, I think it's probably easier just to have the hail version bump in this PR as well...think Daniel's PR is just doing us a favor...

2.1.9 is a reverted version. If that ever published to gcr, it would cause conflicts. At least, it happened to my previous PR: https://github.com/DataBiosphere/terra-docker/pull/337#issuecomment-1165930606

**Comment by Qi77Qi** [comment]
@yonghaoy. `2.1.9` was never published properly

**Comment by yonghaoy** [comment]
> @yonghaoy 2.1.9 is fine to use. regarding #350, I think it's probably easier just to have the hail version bump in this PR as well...think Daniel's PR is just doing us a favor...

@tarekmamdouh do you mind to also bump Hail version in the same PR?

**Comment by tarekmamdouh** [comment]
@yonghaoy I can do that, do you know which hail version should we use? also is there a way that I can test that it works, or the circle tests should be sufficient?

**Comment by Qi77Qi** [comment]
@tarekmamdouh  it should be pretty safe to bump hail version...and typically hail version bumps have nice bug fixes...we have some hail tests in leo repo...so you don't need to do extra work for verify things here for hail

**Comment by Qi77Qi** [comment]
https://github.com/DataBiosphere/terra-docker/pull/350/files#diff-df40bbb7ec38ec9c9fcdba2e7f8375b32309e761e675b54d5182f63b023b23b0R50 is the target version

**Comment by tarekmamdouh** [comment]
@Qi77Qi  thank you, so I see your PR has 2.1.9 and 2.1.10 in CHANGELOG.md, this would cause conflict with my PR. Do you want to merge first, so that I can rebase my branch and resolve the conflict?

Also once I merge and get a release out, I'll update the jupyter image in RW, and the cached image which will take care of bumping the hail version, @yonghaoy can you please confirm my understanding here.

**Comment by tarekmamdouh** [comment]
> > @Qi77Qi thank you, so I see your PR has 2.1.9 and 2.1.10 in CHANGELOG.md, this would cause conflict with my PR. Do you want to merge first, so that I can rebase my branch and resolve the conflict?
> > Also once I merge and get a release out, I'll update the jupyter image in RW, and the cached image which will take care of bumping the hail version, @yonghaoy can you please confirm my understanding here.
> 
> I think we want to close #350 and move that change into your PR. That saves the effort of "building new image and getting it cached"

yep, I update the hail version in this PR, we need to close the other one. I am working on building the new image and getting it cached

**Review by Qi77Qi — APPROVED** [review]
thanks @tarekmamdouh ! change looks good...one thing to look out for is the jenkins job for building the image might fail...it failed last time, which was the reason we had to revert 2.1.9 previously..so just keep an eye on the CI

**Pull request merged**
