### PR TITLE
[SUP-496] Reverted AOU changelog and version.

### PR DESCRIPTION
**Pull request by n8landolt**

### CODE REVIEW

**Review by Qi77Qi — COMMENTED** [review]
https://github.com/DataBiosphere/terra-docker/blob/master/config/conf.json#L146 needs to be reverted if we intend to revert

**Review by Qi77Qi — APPROVED** [review]

**Comment by yonghaoy** [comment]
@Qi77Qi @n8landolt 
We had few conflicts issues before when reusing the a reversed version number. 
I think we should flag any version created in this PR as "do not use" in respective changelogs
Example: https://github.com/DataBiosphere/terra-docker/blob/master/terra-jupyter-aou/CHANGELOG.md#214---2022-06-03t183522582705z

**Comment by Qi77Qi** [comment]
@yonghaoy  2.1.9 version was never published...which is why in this PR, we're reverting that in the changelog

**Comment by yonghaoy** [comment]
> @yonghaoy 2.1.9 version was never published...which is why in this PR, we're reverting that in the changelog

ah, thanks for clarifying!

**Pull request merged**
