### PR TITLE
Update to R-4.0.0

### PR DESCRIPTION
**Pull request by nturaga**
- Update terra-jupyter-r to include the latest release version of R,
R-4.0.0

- terra-jupyter-r also updates the Bioconductor version to release 3.11.

- The terra-jupyter-bioconductor and terra-jupyter-aou images are
updated as a consequence of the updates to the terra-jupyter-r images.

- Updates to CHANGELOG.md in all the files.

### CODE REVIEW

**Comment by rtitle** [comment]
I will take a look at this.

**Comment by rtitle** [comment]
Hey @nturaga, we'd like to bump the `terra-docker` major version for this change. Can you set the version to `1.0.0` for the images you're updating (I believe `terra-jupyter-r`, `terra-jupyter-bioconductor`, `terra-jupyter-gatk`, and `terra-jupyter-aou`)? Benefits of a major version bump:
* it makes it more clear that this is a major change
* it helps us display multiple image versions in Terra UI
* it allows us to make fixes to the legacy R 3.x stack if needed

Once we have the images in place we'll also make Terra UI changes to display R 3.x _and_ R 4.x-based images in the drop-down. Need to work out with @sharmatime what exactly the labels will be and which image will be the default.

Thanks for working on this!

**Comment by nturaga** [comment]
@rtitle Take a look now and see if everything is in order?

**Comment by rtitle** [comment]
Thanks @nturaga, looks correct to me.

I'd like to run Leo automation tests on the `1.0.0` images _before_ merging this, to make sure there are no surprises. I can kick them off now in a dummy branch.

Also we'll need to update some scripts to allow for both R versions to display in the UI. That can be done in a separate PR from this, but I'd still like to hold merging this until we have a Go for the UI update, just to make sure we're not living out of sync for too long. Will follow up on this and keep you posted.

**Comment by nturaga** [comment]
> Thanks @nturaga, looks correct to me.
> 
> I'd like to run Leo automation tests on the `1.0.0` images _before_ merging this, to make sure there are no surprises. I can kick them off now in a dummy branch.
> 
> Also we'll need to update some scripts to allow for both R versions to display in the UI. That can be done in a separate PR from this, but I'd still like to hold merging this until we have a Go for the UI update, just to make sure we're not living out of sync for too long. Will follow up on this and keep you posted.

Sounds good @rtitle

**Comment by rtitle** [comment]
Update! I ran Leo automation tests against all 4 new images (I pushed `1.0.0_tmp` versions to our GCR) and they all passed. So that's looking good.

Following up with Adrian on the UI labels in a little bit… once that's settled this should be good to go.

**Comment by nturaga** [comment]
@rtitle Any update on this?

**Comment by rtitle** [comment]
@nturaga I got the updated image list from Adrian, and I will figure out how to update scripts to display the correct list. I think this can be merged soon though.. however I just saw https://github.com/DataBiosphere/terra-docker/pull/123 and since that PR is updating the base image AND all derived images, I was thinking it should go first.

So order of things:
1. Merge https://github.com/DataBiosphere/terra-docker/pull/123, let CI run and rebuild all images
2. Rebase and merge this PR, let CI run to generate the 1.0.0 images
3. Update scripts and re-run to generate the correct list of images in `gs://terra-docker-image-documentation`
4. When ready, update Terra UI to display the updated images

**Comment by rtitle** [comment]
Hm, I tried to build some of the derived images based on `terra-jupyter-r:1.0.0` and I'm getting an error. This is from `terra-jupyter-gatk:1.0.0`:
```
Fetched 20.7 MB in 6s (3,496 kB/s)
Reading package lists...
E: Failed to fetch https://cloud.r-project.org/bin/linux/ubuntu/bionic-cran40/Packages.bz2  File has unexpected size (21770 != 21390). Mirror sync in progress? [IP: 13.35.82.14 443]
   Hashes of expected file:
    - Filesize:21390 [weak]
    - SHA512:86495e5e847c3bedeab65a1e974d78e4da616f970a1745a36b368eed184e913c21ceadfccd414769b2a78c72e99a7a025c7a992e402bbb0e910cc4a36ccf2a3f
    - SHA256:76a77640e34de0b2821979950f8a6903343ba1bf61b8c9a842734c289664c9f1
    - MD5Sum:6b564d6cae785dfd0b67679e1454deea [weak]
   Release file created at: Thu, 21 May 2020 01:07:52 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -yq --no-install-recommends   python3.7-dev   python-tk   openjdk-8-jdk   tk-dev   libssl-dev   xz-utils   libhdf5-dev   openssl   make   liblzo2-dev   zlib1g-dev   libz-dev   samtools   && update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   && apt-get clean   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

Will look more later..

**Comment by rtitle** [comment]
Hm… actually I tried again and it all worked. Maybe it was transient. 🤷‍♂️

**Comment by nturaga** [comment]
Thanks @rtitle ! I'll let you merge when you are ready.

**Pull request merged**
