### PR TITLE
Updates to jupyter-r image to R 4.1.0 and Bioconductor 3.13

### PR DESCRIPTION
**Pull request by nturaga**
- Update R to 4.1.0 (latest stable release)
- Update Bioconductor to 3.13 (latest stable release)
- Add a library needed for installing a Bioconductor package (RCy3) -- libzmq3-dev

General changes:

- Update CHANGELOG.md (this seems to be an auto-update, not sure I needed to do it)
- Update config.

### CODE REVIEW

**Comment by nturaga** [comment]
The image builds cleanly, and i've checked it. I'm able to push to the `us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:1.0.15` when approved.

**Review by rtitle — APPROVED** [review]
Thanks for updating @nturaga. The changes look fine to me. We can make a separate PR for updating derived images of `terra-jupyter-r`.

**Comment by rtitle** [comment]
@nturaga the CI should automatically push to GCR, no need to do it manually.

**Comment by rtitle** [comment]
Btw @nturaga it's pushed to GCR now: `us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:1.0.15`

**Comment by nturaga** [comment]
Thanks @rtitle. This is great ! Any idea when this and the rstudio image will be available on the UI?

**Comment by gpcarr** [comment]
> Thanks @rtitle. This is great ! Any idea when this and the rstudio image will be available on the UI?

The rstudio image is in dev currently and should become available in prod after today's release at 4pm ET. I can update in slack once that's available. As for these changes, depending on how long the CI takes to run the necessary jobs for these changes to make it leonardo dev, it might go out today as well but I would expect it to go out next release (next week). This [PR](https://github.com/DataBiosphere/leonardo/pull/2162) needs to be merged (once tests pass) and then one more job needs to run that will create an additional automated PR that will also need to be merged. Will keep you updated

**Comment by gpcarr** [comment]
actually looks like for these changes we also need to update the images that are built off of the `terra-jupyter-r` image, so i would say next week for these changes to make it to prod

**Comment by rtitle** [comment]
+1 -- RStudio today, `terra-jupyter-r` next week

**Pull request merged**
