### PR TITLE
Update terra-jupyter-aou to Hail 0.2.130

### PR DESCRIPTION
**Pull request by daniel-goldstein**

### CODE REVIEW

**Review by yonghaoy — APPROVED** [review]

**Comment by yonghaoy** [comment]
@LizBaldo @jdcanas  GHA failed when getting GCP credential. Can you help to check. Also I do not have permission to force merge a PR, would need your help if this change LG

**Comment by LizBaldo** [comment]
The secret might have been moved, I will need to ask Devops and will get back to you shortly with the updated secret

**Comment by yonghaoy** [comment]
> The secret might have been moved, I will need to ask Devops and will get back to you shortly with the updated secret

Thanks. btw, secret might be managed here: https://github.com/broadinstitute/terraform-ap-deployments/blob/master/github/tfvars/databiosphere-terra-docker.tfvars

**Comment by LizBaldo** [comment]
@yonghaoy you need to update the actions as suggested by Devops

**Comment by LizBaldo** [comment]
You need actions/checkout@v4 and google-github-actions/auth@v2

**Comment by yonghaoy** [comment]
Turns out github secret does not work with folk repo. Close this and will use https://github.com/DataBiosphere/terra-docker/pull/485 instead

**Pull request closed without merging**
