### PR TITLE
Fix multipart Jupyter uploads

### PR DESCRIPTION
**Pull request by calbach**
Jupyter's new(?) [default](https://jupyter-notebook.readthedocs.io/en/stable/config.html) file manager is `LargeFileManager`. This supports multipart chunked uploads, which get triggered when a user attempts to upload a file greater than a certain size via the Jupyter UI. Before this change, each chunk would overwrite eachother, resulting in a file which is the tail chunk of the upload.

As a minor optimization, just skip straight to the base manager if we see intermediate chunks.

Also, while I'm here, delete the long-deprecated `DelocalizingContentsManager` (commits are split out, let me know if you prefer separate PRs).

### CODE REVIEW

**Review by Qi77Qi — APPROVED** [review]
thanks for fixing!

**Review by rtitle — APPROVED** [review]
Looks good to me 👍 

This will require a rebuild of all images; however we're doing that anyway with https://github.com/DataBiosphere/terra-docker/pull/251. Shall we merge this first to sneak it in?

**Comment by calbach** [comment]
@rtitle I'll let you click the merge button so I don't interfere with your ongoing operations. From AoU's perspective, would definitely be great to get this fix as soon as we're able.

**Comment by rtitle** [comment]
No worries -- this PR is included in the version bump from the other PR. The CI is running now..

**Pull request merged**
